name: Update Builderer Documentation

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Setup git
        run: |
          git config --global user.name "Florian Sattler"
          git config --global user.email "florian-sattler@users.noreply.github.com"

      - name: Update Docs
        run: mkdocs gh-deploy
