name: Check builderer package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: fiddling around
        run: |
          git config --get user.name
          git config --get user.email
          env | sort
